"""Remove registration_fee from marathon_event and add marathon_distance table

Revision ID: 097986bd8379
Revises: 138eec8ecdd9
Create Date: 2025-11-12 01:19:17.611839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '097986bd8379'
down_revision = '138eec8ecdd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marathon_event', schema=None) as batch_op:
        batch_op.drop_column('registration_fee')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marathon_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_fee', mysql.FLOAT(), nullable=False))

    # ### end Alembic commands ###
