"""Add price to MarathonDistance

Revision ID: 138eec8ecdd9
Revises: 79c78a4fe380
Create Date: 2025-11-12 00:34:16.744581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138eec8ecdd9'
down_revision = '79c78a4fe380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marathon_distance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=False))
        batch_op.create_unique_constraint('unique_distance_per_marathon', ['marathon_id', 'distance'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marathon_distance', schema=None) as batch_op:
        batch_op.drop_constraint('unique_distance_per_marathon', type_='unique')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
