"""Add status to payment_proof

Revision ID: 2b9f527c984a
Revises: 709e09cb269d
Create Date: 2025-10-30 00:54:04.720192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9f527c984a'
down_revision = '709e09cb269d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_proof', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_proof', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
