"""Add bib_number and unique constraint

Revision ID: 79c78a4fe380
Revises: 2b9f527c984a
Create Date: 2025-11-11 20:05:28.841140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c78a4fe380'
down_revision = '2b9f527c984a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marathon_distance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marathon_id', sa.Integer(), nullable=False),
    sa.Column('distance', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['marathon_id'], ['marathon_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marathon_tshirt_size',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marathon_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['marathon_id'], ['marathon_event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tshirt_size', sa.String(length=10), nullable=True))
        batch_op.create_unique_constraint('unique_bib_per_marathon', ['marathon_id', 'bib_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint('unique_bib_per_marathon', type_='unique')
        batch_op.drop_column('tshirt_size')
        batch_op.drop_column('distance')

    op.drop_table('marathon_tshirt_size')
    op.drop_table('marathon_distance')
    # ### end Alembic commands ###
