"""Add amount column to payment_proof

Revision ID: af8c77c7ffd5
Revises: 0bfef0ca03a8
Create Date: 2025-11-13 15:38:45.256325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8c77c7ffd5'
down_revision = '0bfef0ca03a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_proof', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_proof', schema=None) as batch_op:
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
